"""Compile editable mission text to ROM data; reject text we cannot display."""
import json
from pathlib import Path

source = json.loads(Path('data/training.json').read_text())
missions = source['missions']
if len(missions) != 12:
    raise ValueError('Training progression requires twelve scenarios')
modes = ['DEFENSE', 'RAID', 'ESCORT', 'CHASE', 'SURVIVAL', 'RESCUE', 'EVADE', 'SABOTAGE', 'BOSS']
out = ['/* Generated by tools/content.py. Edit data/training.json. */', '#include "game.h"',
       'const char *const mode_names[9] = {' + ','.join(json.dumps(m) for m in modes) + '};',
       'const Mission missions[MISSION_COUNT] = {']
for m in missions:
    fields = []
    for key in ['title', 'brief', 'hint', 'debrief']:
        value = m[key].upper()
        if any(c not in "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,:;!?'-/()" for c in value):
            raise ValueError(f'Unsupported glyph in {key}: {value}')
        if key in ('title', 'hint') and len(value) > 20:
            raise ValueError(f'{key} exceeds screen width')
        if key in ('brief', 'debrief'):
            import textwrap
            if len(textwrap.wrap(value, 18)) > 11:
                raise ValueError(f'{key} exceeds dialog page: {m["title"]}')
        fields.append(json.dumps(value))
    if m['type'] not in modes or m['layout'] not in range(3) or not 1 <= m['seconds'] <= 600:
        raise ValueError(f'Invalid mission parameters: {m["title"]}')
    fields += [m['type']] + [str(m[k]) for k in ['layout', 'seconds', 'goal', 'difficulty']]
    out.append('    {' + ', '.join(fields) + '},')
out.append('};')
Path('build/missions.c').write_text('\n'.join(out) + '\n')
print('Compiled 12 non-canonical training scenarios')
